<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('words')->insert([
            ['id' => 1, 'english' => 'bribe', 'phonetic symbol' => 'bráib', 'japanese' => '他動)〜に賄賂を贈る', 'japanese2' => '名)賄賂', 'english sentence' => 'The corrupt factory owner tried to bribe the local official.', 'japanese sentence' => '堕落した工場主は地元の役人を買収しようとした。', 'voice_script' => NULL, 'level' => 'Pre-intermediate 6.0~', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 2, 'english' => 'strain', 'phonetic symbol' => 'stréin', 'japanese' => '名)緊張', 'japanese2' => '他動)~を緊張させる', 'english sentence' => 'He felt the strain of living in an alien culture.', 'japanese sentence' => '彼は異文化の中で暮らす緊張を感じた', 'voice_script' => NULL, 'level' => 'Elementary 5.5~', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 3, 'english' => 'bishop', 'phonetic symbol' => 'bíʃəp', 'japanese' => '名)主教、司教', 'japanese2' => NULL, 'english sentence' => 'The bishop of Westminster made a moving speech this morning.', 'japanese sentence' => 'ウエストミンスターの主教は今朝感動的な演説を行った。', 'voice_script' => NULL, 'level' => 'Intermediate 6.5~', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 4, 'english' => 'dioxide', 'phonetic symbol' => 'daiɔ́ksaid', 'japanese' => '名)二酸化物', 'japanese2' => NULL, 'english sentence' => 'Levels of carbon dioxide have increased dramatically in developing countries.', 'japanese sentence' => '発展途上国では二酸化炭素量が劇的に増えた。', 'voice_script' => NULL, 'level' => 'Upper-intermediate 7.0~', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 5, 'english' => 'relevant', 'phonetic symbol' => 'réləvənt', 'japanese' => '形)〜に関係がある', 'japanese2' => NULL, 'english sentence' => 'The judge decided that the evidence was not relevant to the case', 'japanese sentence' => '裁判官はその証拠は訴訟に関連がないとの判断を下した', 'voice_script' => NULL, 'level' => 'Pre-intermediate 6.0~', 'created_at' => '2023-10-05 14:33:44', 'updated_at' => '2023-10-06 14:33:44'],
            ['id' => 6, 'english' => 'comprehend', 'phonetic symbol' => 'kɑ́mprɪhénd', 'japanese' => '他動)〜を理解する', 'japanese2' => '', 'english sentence' => 'She couldn\'t comprehend why he was behaving so irrationally.', 'japanese sentence' => '彼がなぜそんなに非合理的に振る舞うのか彼女には理解できなかった。', 'voice_script' => NULL, 'level' => 'Intermediate 6.5~', 'created_at' => '2023-10-05 14:35:44', 'updated_at' => '2023-10-06 14:35:44'],
            ['id' => 7, 'english' => 'navigate', 'phonetic symbol' => 'nǽvɪgèit', 'japanese' => '自動)進路を決める', 'japanese2' => '他動)〜を操縦する', 'english sentence' => 'He navigated the ship through the treacherous waters.', 'japanese sentence' => '彼は危険な水域を船で進んだ。', 'voice_script' => NULL, 'level' => 'Upper-intermediate 7.0~', 'created_at' => '2023-10-05 14:36:44', 'updated_at' => '2023-10-06 14:36:44'],
            ['id' => 8, 'english' => 'enhance', 'phonetic symbol' => 'ɪnhǽns', 'japanese' => '他動)〜を高める', 'japanese2' => '', 'english sentence' => 'The company is taking steps to enhance productivity.', 'japanese sentence' => 'その会社は生産性を高めるための手段を講じている。', 'voice_script' => NULL, 'level' => 'Intermediate 6.5~', 'created_at' => '2023-10-05 15:00:44', 'updated_at' => '2023-10-06 15:00:44'],
            ['id' => 9, 'english' => 'perceive', 'phonetic symbol' => 'pərsíːv', 'japanese' => '他動)〜を知覚する', 'japanese2' => '', 'english sentence' => 'It is often difficult to perceive what is right.', 'japanese sentence' => '正しいことを知覚するのはしばしば難しい。', 'voice_script' => NULL, 'level' => 'Upper-intermediate 7.0~', 'created_at' => '2023-10-05 15:10:44', 'updated_at' => '2023-10-06 15:10:44'],
            ['id' => 10, 'english' => 'compromise', 'phonetic symbol' => 'kɑ́mprəmàɪz', 'japanese' => '名)妥協', 'japanese2' => '自動)妥協する', 'english sentence' => 'They reached a compromise after hours of debate.', 'japanese sentence' => '彼らは数時間の討論の後、妥協に達した。', 'voice_script' => NULL, 'level' => 'Intermediate 7.0~', 'created_at' => '2023-10-05 15:20:44', 'updated_at' => '2023-10-06 15:20:44'],
            ['id' => 11, 'english' => 'integrity', 'phonetic symbol' => 'ɪntégrəti', 'japanese' => '名)誠実、正直', 'japanese2' => '', 'english sentence' => 'She is known for her integrity and dedication.', 'japanese sentence' => '彼女はその誠実さと献身的な態度で知られている。', 'voice_script' => NULL, 'level' => 'Upper-intermediate 7.5~', 'created_at' => '2023-10-05 15:30:44', 'updated_at' => '2023-10-06 15:30:44'],
            ['id' => 12, 'english' => 'constrain', 'phonetic symbol' => 'kənstréin', 'japanese' => '他動)〜を強いる', 'japanese2' => '', 'english sentence' => 'Lack of funding constrains our options.', 'japanese sentence' => '資金不足が私たちの選択肢を制限している。', 'voice_script' => NULL, 'level' => 'Advanced 8.0~', 'created_at' => '2023-10-05 15:40:44', 'updated_at' => '2023-10-06 15:40:44'],
            ['id' => 13, 'english' => 'innovate', 'phonetic symbol' => 'ínəvèit', 'japanese' => '自動)革新する', 'japanese2' => '', 'english sentence' => 'The tech industry continues to innovate.', 'japanese sentence' => '技術産業は革新を続けている。', 'voice_script' => NULL, 'level' => 'Advanced 8.0~', 'created_at' => '2023-10-05 15:50:44', 'updated_at' => '2023-10-06 15:50:44'],
            ['id' => 14, 'english' => 'persistent', 'phonetic symbol' => 'pərsístənt', 'japanese' => '形)しつこい、持続的な', 'japanese2' => '', 'english sentence' => 'Her persistent efforts paid off.', 'japanese sentence' => '彼女の持続的な努力が報われた。', 'voice_script' => NULL, 'level' => 'Intermediate 6.5~', 'created_at' => '2023-10-06 16:00:00', 'updated_at' => '2023-10-07 16:00:00'],
            ['id' => 15, 'english' => 'rational', 'phonetic symbol' => 'rǽʃnəl', 'japanese' => '形)合理的な', 'japanese2' => '', 'english sentence' => 'He made a rational decision based on the facts.', 'japanese sentence' => '彼は事実に基づいて合理的な決定をした。', 'voice_script' => NULL, 'level' => 'Intermediate 7.0~', 'created_at' => '2023-10-06 16:10:00', 'updated_at' => '2023-10-07 16:10:00'],
            ['id' => 16, 'english' => 'predominant', 'phonetic symbol' => 'prɪdɑ́mɪnənt', 'japanese' => '形)優勢な', 'japanese2' => '', 'english sentence' => 'Blue is the predominant color in the painting.', 'japanese sentence' => '青がその絵画の優勢な色である。', 'voice_script' => NULL, 'level' => 'Upper-intermediate 7.5~', 'created_at' => '2023-10-06 16:20:00', 'updated_at' => '2023-10-07 16:20:00'],
            ['id' => 17, 'english' => 'subtle', 'phonetic symbol' => 'sʌ́tl', 'japanese' => '形)微妙な', 'japanese2' => '', 'english sentence' => 'The book reveals a subtle understanding of human nature.', 'japanese sentence' => 'その本は人間性についての微妙な理解を明らかにする。', 'voice_script' => NULL, 'level' => 'Upper-intermediate 8.0~', 'created_at' => '2023-10-06 16:30:00', 'updated_at' => '2023-10-07 16:30:00'],
            ['id' => 18, 'english' => 'intrigue', 'phonetic symbol' => 'ɪntríːɡ', 'japanese' => '名)陰謀', 'japanese2' => '他動)〜の興味をそそる', 'english sentence' => 'The mystery story intrigued me.', 'japanese sentence' => 'そのミステリー物語は私の興味をそそった。', 'voice_script' => NULL, 'level' => 'Advanced 8.0~', 'created_at' => '2023-10-06 16:40:00', 'updated_at' => '2023-10-07 16:40:00'],
            ['id' => 19, 'english' => 'fluctuate', 'phonetic symbol' => 'flʌ́ktʃueit', 'japanese' => '自動)変動する', 'japanese2' => '', 'english sentence' => 'Market prices fluctuate based on supply and demand.', 'japanese sentence' => '市場の価格は供給と需要に基づいて変動する。', 'voice_script' => NULL, 'level' => 'Advanced 8.5~', 'created_at' => '2023-10-06 16:50:00', 'updated_at' => '2023-10-07 16:50:00'],
            ['id' => 20, 'english' => 'comprehensive', 'phonetic symbol' => 'kɑ̀mprɪhénsɪv', 'japanese' => '形)包括的な', 'japanese2' => '', 'english sentence' => 'The research was comprehensive and covered many aspects.', 'japanese sentence' => 'その研究は包括的で多くの側面を網羅していた。', 'voice_script' => NULL, 'level' => 'Advanced 8.5~', 'created_at' => '2023-10-06 17:00:00', 'updated_at' => '2023-10-07 17:00:00'],
            ['id' => 21, 'english' => 'subsequent', 'phonetic symbol' => 'sʌ́bsɪkwənt', 'japanese' => '形)その後の', 'japanese2' => '', 'english sentence' => 'Subsequent events confirmed our doubts.', 'japanese sentence' => 'その後の出来事が私たちの疑念を確認した。', 'voice_script' => NULL, 'level' => 'Advanced 9.0~', 'created_at' => '2023-10-06 17:10:00', 'updated_at' => '2023-10-07 17:10:00'],
            ['id' => 22, 'english' => 'prototype', 'phonetic symbol' => 'próʊtətàɪp', 'japanese' => '名)試作品', 'japanese2' => '', 'english sentence' => 'They built a prototype of the new car for testing.', 'japanese sentence' => '彼らはテスト用の新しい車の試作品を作った。', 'voice_script' => NULL, 'level' => 'Advanced 9.0~', 'created_at' => '2023-10-06 17:20:00', 'updated_at' => '2023-10-07 17:20:00'],
            ['id' => 23, 'english' => 'distort', 'phonetic symbol' => 'dɪstɔ́ːrt', 'japanese' => '他動)歪める', 'japanese2' => '', 'english sentence' => 'The loudspeaker seemed to distort his voice.', 'japanese sentence' => 'その拡声器は彼の声を歪めているように思われた。', 'voice_script' => NULL, 'level' => 'Advanced 9.5~', 'created_at' => '2023-10-06 17:30:00', 'updated_at' => '2023-10-07 17:30:00'],
            ['id' => 24, 'english' => 'simulate', 'phonetic symbol' => 'símjəlèit', 'japanese' => '他動)模擬する', 'japanese2' => '', 'english sentence' => 'The scientists simulated the natural process in the lab.', 'japanese sentence' => '科学者たちは実験室でその自然なプロセスを模擬した。', 'voice_script' => NULL, 'level' => 'Advanced 9.5~', 'created_at' => '2023-10-06 17:40:00', 'updated_at' => '2023-10-07 17:40:00'],
            ['id' => 25, 'english' => 'discipline', 'phonetic symbol' => 'dísəplin', 'japanese' => '名)訓練、規律', 'japanese2' => '他動)〜を訓練する', 'english sentence' => 'Discipline is important for any successful team.', 'japanese sentence' => '成功するチームには規律が重要です。', 'voice_script' => NULL, 'level' => 'Pre-intermediate 6.0~', 'created_at' => '2023-10-05 14:50:44', 'updated_at' => '2023-10-06 14:50:44'],
        ]);
    }
}
